/**
 * The word-MIDI blueprint (docs/SPEC.md §1.5): an engine-agnostic Markdown export for the
 * DAW side. It is never pasted into an engine, so it may carry blueprint-only content
 * (`notes`, `harmony`) that no serializer sends. Pure: same inputs, same bytes.
 */
import { beatsPerBar, sectionTimeline } from "./barmath";
import type { Catalog, MusicSpec } from "./ir/types";
import { scrubNames } from "./lineage";

function clock(sec: number): string {
  const total = Math.round(sec);
  return `${Math.floor(total / 60)}:${String(total % 60).padStart(2, "0")}`;
}

/** A bar count or position, whole when it is whole: 16, 32.5, 113.25. */
function amount(n: number): string {
  const rounded = Math.round(n * 100) / 100;
  return String(rounded);
}

/** Bar numbers are 1-based; a pickup or silence makes them fractional. */
function bar(zeroBased: number): string {
  return amount(zeroBased + 1);
}

export function blueprintMarkdown(spec: MusicSpec, catalog: Catalog): string {
  const lock = spec.D6.meterLock;
  const signature = lock.signature;
  const perBar = beatsPerBar(signature);
  const timeline = sectionTimeline(spec.D6.tempo, signature, spec.D7);
  const barSec = (perBar * 60) / spec.D6.tempo.bpm;
  const runtime = timeline.at(-1);
  const runtimeSec = runtime ? (runtime.silenceAfter ?? runtime.body).end : 0;
  const mode = catalog.modes[spec.D6.key.modeId]?.name ?? spec.D6.key.modeId;

  const lines: string[] = [
    `# ${spec.D10.title || "Untitled"} — word-MIDI blueprint`,
    "",
    "Generated by EVAWAVE from MusicSpec IR v1. DAW-side reference; never paste this into an engine.",
    "",
    `Global: ${signature}${lock.enabled ? " (locked)" : ""} · ${spec.D6.tempo.bpm} BPM ${lock.feel} · ${spec.D6.key.tonic} ${mode} · runtime ${clock(runtimeSec)} (${amount(runtimeSec / barSec)} bars)`,
  ];
  if (spec.D6.harmony.length) lines.push("", "Harmony:", ...spec.D6.harmony.map((h) => `- ${h}`));

  timeline.forEach((timing, i) => {
    const s = timing.section;
    const startBar = timing.body.start / barSec;
    const endBar = timing.body.end / barSec;
    lines.push("", `### Section ${i + 1} · ${s.label} · bars ${bar(startBar)}–${bar(endBar - 1)} · ${clock(timing.body.start)}–${clock(timing.body.end)}`);
    lines.push(`- Dynamics: ${s.dynamics}`);
    if (s.modeId) lines.push(`- Mode: ${catalog.modes[s.modeId]?.name ?? s.modeId}`);
    if (s.pickupBefore) lines.push(`- Pickup (${s.pickupBefore.beats} beats, back to ${s.pickupBefore.returnTo}): ${s.pickupBefore.content}`);
    for (const cue of s.cues) {
      if (cue.slot === "pocket" && s.openPocket.kind !== "none") lines.push(`- Pocket: ${s.openPocket.note ?? s.openPocket.kind}`);
      else if (cue.text) lines.push(`- ${cue.slot}${cue.phrases?.length ? ` (phrases ${cue.phrases.join(", ")})` : ""}: ${cue.text}`);
    }
    if (s.contrast) {
      const c = s.contrast;
      lines.push(`- Contrast (${c.position === "end" ? "last" : "first"} ${c.bars} bars, ${c.label ?? c.styleId}): ${[...c.changes, c.returnRule].join(", ")}`);
    }
    if (s.harmony) lines.push(`- Harmony: ${s.harmony}`);
    s.notes?.forEach((note) => lines.push(`- Note: ${note}`));
    if (s.transitionOut.kind !== "none") lines.push(`- Transition out: ${s.transitionOut.note ?? s.transitionOut.kind}`);
    if (s.silenceAfter) lines.push(`- Silence: ${s.silenceAfter.beats} beat(s) at the ${s.silenceAfter.position}`);
  });
  return scrubNames(`${lines.join("\n")}\n`, catalog.lineageNames);
}
