/**
 * Browser implementations of the import steps (docs/SPEC.md §1.7): Web Audio decoding and
 * the Origin Private File System for the blob. Nothing here performs a network request.
 */
import type { PcmAudio } from "@/core/musicspec/analysis/wav";
import type { AudioFeatures } from "@/core/musicspec/ir/types";

import type { AnalysisReply, AnalysisRequest } from "./analysis.worker";
import { sha256Hex, type ImportDeps } from "./import";

export async function decodeWithWebAudio(bytes: ArrayBuffer): Promise<PcmAudio> {
  const context = new AudioContext();
  try {
    const buffer = await context.decodeAudioData(bytes.slice(0));
    const channelData = Array.from({ length: buffer.numberOfChannels }, (_, c) => buffer.getChannelData(c));
    let samples = channelData[0] ?? new Float32Array(0);
    if (channelData.length > 1) {
      samples = new Float32Array(buffer.length);
      for (const channel of channelData) {
        for (let i = 0; i < channel.length; i++) samples[i] = (samples[i] as number) + (channel[i] as number) / channelData.length;
      }
    }
    return { sampleRate: buffer.sampleRate, samples, channels: buffer.numberOfChannels, channelData };
  } finally {
    await context.close();
  }
}

/** The bundled analysis worker (generated by scripts/build-analysis-worker.mjs; do not edit). */
export const ANALYSIS_WORKER_URL = "/workers/analysis.worker.js";

/**
 * Analyses decoded audio in a Web Worker, so the page stays responsive through a long track.
 * Aborting `signal` terminates the worker, so a newer file choice stops the old analysis at
 * once. The sample buffers are transferred, not copied (each once: a mono mix is its own
 * channel), and are unusable here afterwards.
 */
export function analyseInWorker(pcm: PcmAudio, signal?: AbortSignal): Promise<AudioFeatures> {
  return new Promise((resolve, reject) => {
    signal?.throwIfAborted();
    const worker = new Worker(ANALYSIS_WORKER_URL, { type: "module" });
    const onAbort = () => {
      finish();
      reject(signal?.reason);
    };
    const finish = () => {
      worker.terminate();
      signal?.removeEventListener("abort", onAbort);
    };
    signal?.addEventListener("abort", onAbort, { once: true });
    worker.onmessage = (event: MessageEvent<AnalysisReply>) => {
      finish();
      if (event.data.ok) resolve(event.data.features);
      else reject(new Error(event.data.message));
    };
    worker.onerror = (event) => {
      finish();
      reject(new Error(event.message || "the analysis worker failed"));
    };
    const request: AnalysisRequest = { samples: pcm.samples, sampleRate: pcm.sampleRate, channels: pcm.channelData };
    const buffers = [...new Set([pcm.samples, ...pcm.channelData].map((array) => array.buffer as ArrayBuffer))];
    worker.postMessage(request, buffers);
  });
}

/** The fallback store: blobs this tab could not write to OPFS, keyed by sha256. */
const tabMemory = new Map<string, Blob>();

/**
 * Keeps the file in OPFS under audio/<sha256>; falls back to memory where OPFS is missing.
 * The import screen calls it once a library save of a profile from the file succeeds.
 */
export async function storeInOpfs(sha256: string, file: Blob): Promise<"opfs" | "memory"> {
  try {
    const root = await navigator.storage.getDirectory();
    const dir = await root.getDirectoryHandle("audio", { create: true });
    const handle = await dir.getFileHandle(sha256, { create: true });
    const existing = await handle.getFile();
    if (existing.size !== file.size) {
      const writable = await handle.createWritable();
      await writable.write(file);
      await writable.close();
    }
    return "opfs";
  } catch {
    // Some browsers (and private windows) have no OPFS or no createWritable; the analysis
    // still works, and the blob stays in this tab's memory only.
    tabMemory.set(sha256, file);
    return "memory";
  }
}

const isDomError = (error: unknown, name: string) => error instanceof DOMException && error.name === name;

/**
 * Removes the local copy of `sha256` (OPFS and the in-tab fallback), for when its library
 * record is deleted. No OPFS API, a private window's refusal (storeInOpfs could keep nothing
 * there either), or nothing stored under the hash is not an error; any other failure (a lock,
 * an I/O error) rejects, so the caller can keep the record and retry. OPFS is
 * per origin, so another account on this browser that imported the same file shares the copy;
 * it can import the file again.
 */
export async function removeLocalAudio(sha256: string): Promise<void> {
  tabMemory.delete(sha256);
  if (typeof navigator === "undefined" || typeof navigator.storage?.getDirectory !== "function") return;
  let root: FileSystemDirectoryHandle;
  try {
    root = await navigator.storage.getDirectory();
  } catch (error) {
    if (isDomError(error, "SecurityError")) return;
    throw error;
  }
  try {
    await (await root.getDirectoryHandle("audio")).removeEntry(sha256);
  } catch (error) {
    if (!isDomError(error, "NotFoundError")) throw error;
  }
}

/**
 * A copy, in memory, of the local audio for `sha256`: the in-tab blob, or the OPFS file's
 * bytes (read now, since the file handle stops being readable once its entry is removed).
 * Undefined when nothing is kept here.
 */
async function readLocalAudio(sha256: string): Promise<Blob | undefined> {
  const inTab = tabMemory.get(sha256);
  if (inTab) return inTab;
  if (typeof navigator === "undefined" || typeof navigator.storage?.getDirectory !== "function") return undefined;
  try {
    const dir = await (await navigator.storage.getDirectory()).getDirectoryHandle("audio");
    const file = await (await dir.getFileHandle(sha256)).getFile();
    return new Blob([await file.arrayBuffer()], { type: file.type });
  } catch (error) {
    if (isDomError(error, "NotFoundError") || isDomError(error, "SecurityError")) return undefined;
    throw error;
  }
}

/**
 * Deletes a library file record and its local audio as one recoverable step. The local copy
 * is read into memory and removed first, so a failed removal keeps the record (and its hash)
 * for a retry. If deleting the record then fails, the copy is stored again, so a failure
 * leaves both stores as they were.
 */
export async function deleteWithLocalAudio(sha256: string, deleteRecord: () => Promise<void>): Promise<void> {
  const copy = await readLocalAudio(sha256);
  await removeLocalAudio(sha256);
  try {
    await deleteRecord();
  } catch (error) {
    if (copy) await storeInOpfs(sha256, copy);
    throw error;
  }
}

/** The blob the memory fallback holds for `sha256`, if this tab kept one. */
export function blobInTab(sha256: string): Blob | undefined {
  return tabMemory.get(sha256);
}

export const browserImportDeps: ImportDeps = {
  decode: decodeWithWebAudio,
  analyse: analyseInWorker,
  digest: sha256Hex,
  now: () => new Date().toISOString(),
};
