/**
 * Browser implementations of the import steps (docs/SPEC.md §1.7): Web Audio decoding and
 * the Origin Private File System for the blob. Nothing here performs a network request.
 */
import type { PcmAudio } from "@/core/musicspec/analysis/wav";
import type { AudioFeatures } from "@/core/musicspec/ir/types";

import type { AnalysisReply, AnalysisRequest } from "./analysis.worker";
import { sha256Hex, type ImportDeps } from "./import";

export async function decodeWithWebAudio(bytes: ArrayBuffer): Promise<PcmAudio> {
  const context = new AudioContext();
  try {
    const buffer = await context.decodeAudioData(bytes.slice(0));
    const channelData = Array.from({ length: buffer.numberOfChannels }, (_, c) => buffer.getChannelData(c));
    let samples = channelData[0] ?? new Float32Array(0);
    if (channelData.length > 1) {
      samples = new Float32Array(buffer.length);
      for (const channel of channelData) {
        for (let i = 0; i < channel.length; i++) samples[i] = (samples[i] as number) + (channel[i] as number) / channelData.length;
      }
    }
    return { sampleRate: buffer.sampleRate, samples, channels: buffer.numberOfChannels, channelData };
  } finally {
    await context.close();
  }
}

/** The bundled analysis worker (generated by scripts/build-analysis-worker.mjs; do not edit). */
export const ANALYSIS_WORKER_URL = "/workers/analysis.worker.js";

/**
 * Analyses decoded audio in a Web Worker, so the page stays responsive through a long track.
 * Aborting `signal` terminates the worker, so a newer file choice stops the old analysis at
 * once. The sample buffers are transferred, not copied (each once: a mono mix is its own
 * channel), and are unusable here afterwards.
 */
export function analyseInWorker(pcm: PcmAudio, signal?: AbortSignal): Promise<AudioFeatures> {
  return new Promise((resolve, reject) => {
    signal?.throwIfAborted();
    const worker = new Worker(ANALYSIS_WORKER_URL, { type: "module" });
    const onAbort = () => {
      finish();
      reject(signal?.reason);
    };
    const finish = () => {
      worker.terminate();
      signal?.removeEventListener("abort", onAbort);
    };
    signal?.addEventListener("abort", onAbort, { once: true });
    worker.onmessage = (event: MessageEvent<AnalysisReply>) => {
      finish();
      if (event.data.ok) resolve(event.data.features);
      else reject(new Error(event.data.message));
    };
    worker.onerror = (event) => {
      finish();
      reject(new Error(event.message || "the analysis worker failed"));
    };
    const request: AnalysisRequest = { samples: pcm.samples, sampleRate: pcm.sampleRate, channels: pcm.channelData };
    const buffers = [...new Set([pcm.samples, ...pcm.channelData].map((array) => array.buffer as ArrayBuffer))];
    worker.postMessage(request, buffers);
  });
}

/**
 * Names one account's local copy of a file. OPFS is per origin, so two accounts on one
 * browser can save the same file: each copy lives under its owner, at audio/<ownerId>/<sha256>,
 * and deleting one account's record never removes another account's copy.
 */
export interface LocalAudioKey {
  ownerId: string;
  sha256: string;
}

/** The fallback store: blobs this tab could not write to OPFS, keyed by owner and sha256. */
const tabMemory = new Map<string, Blob>();

const tabKey = ({ ownerId, sha256 }: LocalAudioKey) => `${ownerId}/${sha256}`;

let channel: BroadcastChannel | undefined;

/**
 * Tabs of this origin tell each other when a fallback copy in memory is no longer needed:
 * after its record is deleted, or once OPFS holds the file. Another tab's memory is its own,
 * and no lock can reach it. A tab starts listening once it holds such a copy.
 */
function audioChannel(): BroadcastChannel | undefined {
  if (channel || typeof BroadcastChannel !== "function") return channel;
  channel = new BroadcastChannel("evawave:local-audio");
  channel.onmessage = (event: MessageEvent<{ drop?: unknown }>) => {
    if (typeof event.data?.drop === "string") tabMemory.delete(event.data.drop);
  };
  // Node keeps a process running while a channel is open; browsers have no unref.
  (channel as unknown as { unref?: () => void }).unref?.();
  return channel;
}

async function ownerDirectory(root: FileSystemDirectoryHandle, ownerId: string, create: boolean): Promise<FileSystemDirectoryHandle> {
  return (await root.getDirectoryHandle("audio", { create })).getDirectoryHandle(ownerId, { create });
}

/**
 * Keeps the file in OPFS under audio/<ownerId>/<sha256>; falls back to memory where OPFS is
 * missing. The import screen calls it once a library save of a profile from the file succeeds.
 */
export async function storeInOpfs(key: LocalAudioKey, file: Blob): Promise<"opfs" | "memory"> {
  try {
    const dir = await ownerDirectory(await navigator.storage.getDirectory(), key.ownerId, true);
    const handle = await dir.getFileHandle(key.sha256, { create: true });
    const existing = await handle.getFile();
    if (existing.size !== file.size) {
      const writable = await handle.createWritable();
      await writable.write(file);
      await writable.close();
    }
    // OPFS holds it now, so an earlier fallback copy, here or in another tab, would only keep
    // the recording in memory.
    tabMemory.delete(tabKey(key));
    audioChannel()?.postMessage({ drop: tabKey(key) });
    return "opfs";
  } catch {
    // Some browsers (and private windows) have no OPFS or no createWritable; the analysis
    // still works, and the blob stays in this tab's memory only.
    tabMemory.set(tabKey(key), file);
    audioChannel();
    return "memory";
  }
}

/**
 * The `store` step for a save made while holding `ownerId`'s turn: keeps the audio when the
 * rows were written for that account. If another tab switched accounts mid-save, the rows
 * belong to the new account, whose turn this is not, so nothing is kept and that account can
 * add the audio by importing the file again.
 */
export function keepAudioFor(ownerId: string): (saved: LocalAudioKey, audio: Blob) => Promise<"opfs" | "memory" | "not-kept"> {
  return async (saved, audio) => (saved.ownerId === ownerId ? storeInOpfs(saved, audio) : "not-kept");
}

const isDomError = (error: unknown, name: string) => error instanceof DOMException && error.name === name;

/**
 * Removes this account's local copy of a file (OPFS and the in-tab fallback), for when its
 * library record is deleted. No OPFS API, a private window's refusal (storeInOpfs could keep
 * nothing there either), or nothing stored under the key is not an error; any other failure
 * (a lock, an I/O error) rejects and removes nothing, so the caller can keep the record and
 * retry.
 */
export async function removeLocalAudio(key: LocalAudioKey): Promise<void> {
  if (typeof navigator !== "undefined" && typeof navigator.storage?.getDirectory === "function") await removeFromOpfs(key);
  // Last, so a failed OPFS removal keeps the in-tab copy (the only one, after a fallback).
  tabMemory.delete(tabKey(key));
}

async function removeFromOpfs(key: LocalAudioKey): Promise<void> {
  let root: FileSystemDirectoryHandle;
  try {
    root = await navigator.storage.getDirectory();
  } catch (error) {
    if (isDomError(error, "SecurityError")) return;
    throw error;
  }
  try {
    await (await ownerDirectory(root, key.ownerId, false)).removeEntry(key.sha256);
  } catch (error) {
    if (!isDomError(error, "NotFoundError")) throw error;
  }
}

/**
 * A copy, in memory, of this account's local audio for a file: the in-tab blob, or the OPFS
 * file's bytes (read now, since the file handle stops being readable once its entry is
 * removed). Undefined when nothing is kept here.
 */
async function readLocalAudio(key: LocalAudioKey): Promise<Blob | undefined> {
  const inTab = tabMemory.get(tabKey(key));
  if (inTab) return inTab;
  if (typeof navigator === "undefined" || typeof navigator.storage?.getDirectory !== "function") return undefined;
  try {
    const dir = await ownerDirectory(await navigator.storage.getDirectory(), key.ownerId, false);
    const file = await (await dir.getFileHandle(key.sha256)).getFile();
    return new Blob([await file.arrayBuffer()], { type: file.type });
  } catch (error) {
    if (isDomError(error, "NotFoundError") || isDomError(error, "SecurityError")) return undefined;
    throw error;
  }
}

/** Deletes in flight, by key, so a repeated delete of the same file joins the first. */
const deleting = new Map<string, Promise<void>>();

/**
 * Runs `task` holding a Web Lock named for this account's file, so a delete and a save that
 * keeps the audio never interleave, in this tab or across tabs of the origin. Where the API
 * is missing, runs it directly.
 */
export async function inTurnForLocalAudio<T>(key: LocalAudioKey, task: () => Promise<T>): Promise<T> {
  const locks = typeof navigator === "undefined" ? undefined : navigator.locks;
  if (typeof locks?.request !== "function") return task();
  return await locks.request(`evawave:local-audio:${tabKey(key)}`, task);
}

/**
 * Deletes a library file record and its local audio as one recoverable step. The local copy
 * is read into memory and removed first, so a failed removal keeps the record (and its hash)
 * for a retry. If deleting the record then fails, the copy is stored again, so a failure
 * leaves both stores as they were; if OPFS will not take it back, the rejection says the audio
 * is held in this tab only. Two deletes of the same file must not overlap: the second
 * would read the copy, find no row, and restore a copy nothing refers to. So a second call in
 * this tab joins the first, and other tabs wait their turn (inTurnForLocalAudio); by then the
 * copy is gone, and a failure there restores nothing.
 */
export function deleteWithLocalAudio(key: LocalAudioKey, deleteRecord: () => Promise<void>): Promise<void> {
  const id = tabKey(key);
  const pending = deleting.get(id);
  if (pending) return pending;
  const run = inTurnForLocalAudio(key, () => deleteOnce(key, deleteRecord)).finally(() => deleting.delete(id));
  deleting.set(id, run);
  return run;
}

async function deleteOnce(key: LocalAudioKey, deleteRecord: () => Promise<void>): Promise<void> {
  const copy = await readLocalAudio(key);
  // Read from OPFS unless the tab held it: then only an OPFS restore puts things back.
  const durable = copy !== undefined && !tabMemory.has(tabKey(key));
  await removeLocalAudio(key);
  try {
    await deleteRecord();
  } catch (error) {
    if (copy && (await storeInOpfs(key, copy)) === "memory" && durable) {
      // The record stays, but its audio went back to this tab only, which closing it loses.
      // Say so, rather than report the failed delete as though nothing had changed.
      const reason = error instanceof Error ? error.message : String(error);
      throw new Error(`${reason} Its audio could not be put back in this browser's storage and is held in this tab only; import the file again to keep it.`, { cause: error });
    }
    throw error;
  }
  audioChannel()?.postMessage({ drop: tabKey(key) });
}

/**
 * Removes this account's local copies whose library record is gone: deleted from another
 * device or browser profile, which cannot reach this device's copy. `known` holds the hashes
 * of the records just loaded. Any other local copy is checked with `hasRecord` while holding
 * its turn, so a truncated list, or a save in another tab, never costs a copy that still has
 * a record. Resolves to the hashes removed.
 */
export async function reconcileLocalAudio(ownerId: string, known: ReadonlySet<string>, hasRecord: (sha256: string) => Promise<boolean>): Promise<string[]> {
  // This tab's fallback copies count too: a delete on another device cannot reach them.
  const prefix = `${ownerId}/`;
  const names = new Set([...tabMemory.keys()].filter((id) => id.startsWith(prefix)).map((id) => id.slice(prefix.length)));
  for (const name of await opfsNames(ownerId)) names.add(name);
  const removed: string[] = [];
  for (const sha256 of [...names].filter((name) => !known.has(name))) {
    const key = { ownerId, sha256 };
    const gone = await inTurnForLocalAudio(key, async () => {
      if (await hasRecord(sha256)) return false;
      await removeLocalAudio(key);
      return true;
    });
    if (gone) removed.push(sha256);
  }
  return removed;
}

/** The names of this account's copies in OPFS; none where OPFS or the directory is missing. */
async function opfsNames(ownerId: string): Promise<string[]> {
  if (typeof navigator === "undefined" || typeof navigator.storage?.getDirectory !== "function") return [];
  let dir: FileSystemDirectoryHandle;
  try {
    dir = await ownerDirectory(await navigator.storage.getDirectory(), ownerId, false);
  } catch (error) {
    if (isDomError(error, "NotFoundError") || isDomError(error, "SecurityError")) return [];
    throw error;
  }
  // Async iteration of a directory is in lib.dom.asynciterable, which this project does not load.
  const names: string[] = [];
  for await (const name of (dir as unknown as { keys(): AsyncIterable<string> }).keys()) names.push(name);
  return names;
}

/** The blob the memory fallback holds for this account's file, if this tab kept one. */
export function blobInTab(key: LocalAudioKey): Blob | undefined {
  return tabMemory.get(tabKey(key));
}

export const browserImportDeps: ImportDeps = {
  decode: decodeWithWebAudio,
  analyse: analyseInWorker,
  digest: sha256Hex,
  now: () => new Date().toISOString(),
};
